services:
  tdengine-tdgpt:
    image: tdengine/tdgpt:latest
    container_name: tdengine-tdgpt
    hostname: tdengine-tdgpt
    restart: always
    environment:
      TZ: "${TZ:-UTC}"
    ports:
      - "6090:6090"
      - "5000:5000"
      - "5001:5001"
    networks:
      - taos_net
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:6090').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  tdengine-tsdb:
    image: tdengine/tsdb-ee:latest
    container_name: tdengine-tsdb
    hostname: tdengine
    restart: always
    environment:
      TZ: "${TZ:-UTC}"
    ports:
      - "6030:6030"
      - "6041:6041"
      - "6060:6060"
    volumes:
      - tdengine_data:/var/lib/taos
      - tdengine_log:/var/log/taos
      - ./init-anode.sql:/docker-entrypoint-initdb.d/init-anode.sql
    networks:
      - taos_net
    depends_on:
      tdengine-tdgpt:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "taos", "-h", "localhost", "-s", "show databases;"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  tdengine-idmp:
    image: tdengine/idmp-ee:latest
    container_name: tdengine-idmp
    restart: always
    depends_on:
      tdengine-tsdb:
        condition: service_healthy
    environment:
      TZ: "${TZ:-UTC}"
      TSDB_URL: "http://tdengine-tsdb:6041"
    ports:
      - "6042:6042"
      - "8082:8082"
    volumes:
      - tdengine_data:/var/lib/taos
      - tdengine_log:/var/log/taos
    networks:
      - taos_net
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:6042').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  taos_net:
    driver: bridge

volumes:
  tdengine_data:
    driver: local
  tdengine_log:
    driver: local