---
# Deploys and start TDengine IDMP.
# Run command: ansible-playbook playbooks/tdengine-idmp.yml --ask-vault-pass -e tdengine_idmp_version=<idmp_version>
# Deploy TDengine IDMP and TDengine Enterprise Edition:
# Run command: ansible-playbook playbooks/tdengine-idmp.yml --ask-vault-pass -e tdengine_idmp_version=<idmp_version> -e deploy_tdengine_tsdb=true -e tdengine_tsdb_version=<tsdb_version>
#  Eg: ansible-playbook playbooks/tdengine-idmp.yml --ask-vault-pass -e tdengine_idmp_version=3.3.7.0 -e deploy_tdengine_tsdb=true -e tdengine_tsdb_version=1.0.0

- import_playbook: tdengine-tsdb.yml
  vars:
    edition: enterprise
    tdengine_tsdb_version: "{{ tdengine_tsdb_version }}"
  when: deploy_tdengine_tsdb is defined and deploy_tdengine_tsdb

- name: Deploy TDengine IDMP
  hosts: tdengine_idmp_servers
  vars_files:
    - ../inventory/group_vars/public.yml
  become: true
  vars:
    download_url: "https://downloads.tdengine.com/tdengine-idmp-enterprise/{{ tdengine_idmp_version }}/tdengine-idmp-enterprise-{{ tdengine_idmp_version }}-linux-generic.tar.gz"
    install_dir: "/usr/local/taos"  # default install_dir
    tdengine_idmp_dl_path: "/tmp"
    required_services:
      - tdengine-idmp-h2
      - tdengine-idmp-chat
      - tdengine-idmp
    check_port: 6042

  tasks:
    - name: Check if temporary directory exists
      ansible.builtin.stat:
        path: "{{ tdengine_idmp_dl_path }}"
      register: temp_dir_stat

    - name: Create temporary directory
      ansible.builtin.file:
        path: "{{ tdengine_idmp_dl_path }}"
        state: directory
        mode: "0755"
      when: not temp_dir_stat.stat.exists

    - name: Check if package already exists
      ansible.builtin.stat:
        path: "{{ tdengine_idmp_dl_path }}/tdengine-idmp-enterprise-{{ tdengine_idmp_version }}-linux-generic.tar.gz"
      register: pkg_check

    - name: Download TDengine IDMP package
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: "{{ tdengine_idmp_dl_path }}/tdengine-idmp-enterprise-{{ tdengine_idmp_version }}-linux-generic.tar.gz"
        mode: "0644"
        timeout: 30

      when: not pkg_check.stat.exists

    - name: Extract TDengine IDMP package
      ansible.builtin.unarchive:
        src: "{{ tdengine_idmp_dl_path }}/tdengine-idmp-enterprise-{{ tdengine_idmp_version }}-linux-generic.tar.gz"
        dest: "{{ tdengine_idmp_dl_path }}"
        remote_src: true

    - name: Run install.sh with -d options
      ansible.builtin.command: "{{ tdengine_idmp_dl_path }}/tdengine-idmp-enterprise-{{ tdengine_idmp_version }}/install.sh -d {{ install_dir }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
      register: install_output
      changed_when:
        - install_output.rc == 0
        - "'already installed' not in (install_output.stdout|default(''))"

    - name: Clean up temporary files
      ansible.builtin.file:
        path: "{{ tdengine_idmp_dl_path }}/tdengine-idmp-enterprise-{{ tdengine_idmp_version }}"
        state: absent

    - name: Start and enable TDengine IDMP services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ required_services }}"
      register: service_status
      retries: 3
      delay: 10
      until: service_status is success

    - name: Verify services are running
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      loop: "{{ required_services }}"
      register: service_check
      failed_when: >
        service_check.failed or
        service_check.status.ActiveState != 'active' or
        service_check.status.SubState != 'running'

    - name: Check if port {{ check_port }} is listening
      ansible.builtin.wait_for:
        host: "127.0.0.1"
        port: "{{ check_port }}"
        state: started
        timeout: 30
      register: port_check
      retries: 5
      delay: 5

    - name: Verify TDengine IDMP installation
      ansible.builtin.stat:
        path: "{{ install_dir }}/idmp/bin"
      register: tdengine_idmp_bin
      failed_when: not tdengine_idmp_bin.stat.exists

    - name: Display deployment validation results
      ansible.builtin.debug:
        msg: |
          Deployment Summary:
          - Services Status:
            {% for item in required_services %}
            {{ item }}: {{ service_check.results[loop.index0].status }}
            {% endfor %}
          - Port {{ check_port }} Status: {{ 'Listening' if port_check is success else 'Not listening' }}
          - Installation Path: {{ install_dir }}/idmp/bin exists? {{ tdengine_idmp_bin.stat.exists | default('false') }}

